server:
  port: 8088
  servlet:
    context-path: /api
spring:
  application:
    name: "demo test"
  datasource:
    # \u521D\u59CB\u5316\u7EBF\u7A0B\u6C60\u6570\u91CF  \u6700\u5927\u6570  \u6700\u5C0F\u6570
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: "jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai"
      password: "root"
      username: "root"
      driver-class-name: com.mysql.jdbc.Driver
      # \u521D\u59CB\u5316\u8FDE\u63A5\u5927\u5C0F
      initial-size: 5
      #\u6700\u5927\u8FDE\u63A5\u6C60\u6570\u91CF
      max-active: 20
      # \u6700\u5C0F\u8FDE\u63A5\u6C60\u6570\u91CF
      min-idle: 3
      # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4 \u5355\u4F4D\u6BEB\u79D2
      max-wait: 60000
      # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2

# ========MP\u914D\u7F6E \u65E0\u9700\u914D\u7F6Emybatis\u4E86============
mybatis-plus:
  # \u5982\u679C\u662F\u653E\u5728src/main/java\u76EE\u5F55\u4E0B classpath:/com/\u4F60\u7684\u5305\u540D/*/mappers/*.xml
  # \u5982\u679C\u653E\u5728 src/main/resources \u4E0B
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      # \u4E3B\u952E\u7C7B\u578B
      id-type: auto
      #\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #\u914D\u7F6E\u8FD4\u56DE\u6570\u636E\u5E93(column\u4E0B\u5212\u7EBF\u547D\u540D&&\u8FD4\u56DEjava\u5B9E\u4F53\u662F\u9A7C\u5CF0\u547D\u540D)\uFF0C\u81EA\u52A8\u5339\u914D\u65E0\u9700as\uFF08\u6CA1\u5F00\u542F\u8FD9\u4E2A\uFF0CSQL\u9700\u8981\u5199as\uFF1A select user_id as userId\uFF09
    map-underscore-to-camel-case: true
    cache-enabled: false
    #\u914D\u7F6EJdbcTypeForNull, oracle\u6570\u636E\u5E93\u5FC5\u987B\u914D\u7F6E
    jdbc-type-for-null: 'null'
#\u914D\u7F6E\u63A7\u5236\u53F0\u6253\u5370\u65E5\u5FD7Debug\uFF0C\u7528\u6765\u67E5\u770Bsql\u5199\u6CA1\u5199\u9519
logging:
  level:
    com.jd.mapper: debug